ifndef MCU
    MCU = atxmega64a4u
endif

C_SRC += alpha_split_util.c

CFLAGS += -DCHECK_PORT=PORTC
CFLAGS += -DCHECK_PIN=PIN1_bm

# VBUS_CHECK pin on pin C1
# CFLAGS += -DI2C_LEFT_PORT=PORTR
# CFLAGS += -DI2C_LEFT_PIN=PIN0_bm

# CFLAGS += -DI2C_RIGHT_PORT=PORTE
# CFLAGS += -DI2C_RIGHT_PIN=PIN3_bm

# CFLAGS += -DUSB_SEL_PORT=PORTE
# CFLAGS += -DUSB_SEL_PIN=PIN2_bm

# CFLAGS += -DUSB_OE_PORT=PORTR
# CFLAGS += -DUSB_OE_PIN=PIN1_bm

#### v2
# Note: USB_SEL is connected to I2C_OE_LEFT
CFLAGS += -DALPHA_SPLIT_V2
CFLAGS += -DI2C_OE_LEFT_PORT=PORTR
CFLAGS += -DI2C_OE_LEFT_PIN=PIN0_bm

CFLAGS += -DI2C_OE_RIGHT_PORT=PORTE
CFLAGS += -DI2C_OE_RIGHT_PIN=PIN3_bm

CFLAGS += -DUSB_OE_PORT=PORTR
CFLAGS += -DUSB_OE_PIN=PIN1_bm
